---
Name: ssp-estimator
---
SilverStripe\Control\Director:
  rules:
    'platform/estimate': SilverStripe\SSP\Estimator
SilverStripe\Platform\WebTier:
  extensions:
    - SilverStripe\SSP\WebTierEstimator
